version: '3'
services:
  mongo:
    image: mongo:4.2.5
    networks:
      - rit-network
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
  service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongdb.host=mongo
    networks:
      - rit-network
    depends_on:
      - mongo
networks:
  rit-network:
    driver: "bridge"